name: TEST

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
  build:
   runs-on: ubuntu-latest 
     
   steps: 
       - uses: actions/checkout@v2
       - name: Python install
         uses: actions/setup-python@v2
       - name: setup package 
         uses: py-actions/flake8@v1
         with:
           path: "scr/main.py"
       - name: result
         run: echo linting is done
        #SO what? 
  test:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Python install
          uses: actions/setup-python@v2
        - name: install pytest
          run: |
             python -m pip install --upgrade pip
             pip install pytest
        - name: run test
          run: pytest /scr/test.py
        - name: result
          run: echo something was happened 

