name: TEST

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
  build:
   runs-on: ubuntu-latest 
     
   steps: 
       - uses: actions/checkout@v2
       - name: Python install
         uses: actions/setup-python@v2
       - name: setup package 
        uses: py-actions/flake8@v1
      
       - name: run tests
         run: flake8 --statistics main.py
       - name: result
         run: echo linting is done