version: 1
jobs: 
  build:
   docker: 
     - image: python
   working directory: ~/repo

   steps: 
    - checkout

    - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install flake8
      
    - run: 
          name: run tests
          command: |
            . venv/bin/activate
            flake8 --exclude=venv* --statistics
           