name: TESTS


on:
  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:    
  Linting: 
      runs-on: ubuntu-latest 
       steps: 
       - uses: actions/checkout@v2
       - name: Python install
         uses: actions/setup-python@v2
       - name: setup package 
         uses: py-actions/flake8@v1
         with:
           path: "scr/main.py"
       - name: result
         run: echo linting is done
        
  testing:
    needs: build
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - name: Python install
          uses: actions/setup-python@v2
        - name: install pytest
          run: |
             python -m pip install --upgrade pip
             pip install pytest
             pip install requests
             pip install pytest-cov
        - name: run test
          run: pytest -vv
          
        - name: result
          run: echo something was happened 
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/build-push-action@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: keton/pytestapi
          tag_with_ref: true